/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub(_replica_done_initializing)
cos_asm_server_stub(_voter_write)
cos_asm_server_stub(_voter_read)
cos_asm_server_stub(_voter_socket)
cos_asm_server_stub(_voter_bind)
cos_asm_server_stub(_voter_accept)

